version: '3'
services:

  mysql:
    container_name: solar-farm-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: top-secret-passwd
    volumes:
      - ./data/mysql:/var/lib/mysql

  cassandra:
    container_name: solar-farm-cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

